#!/bin/bash
set -euo pipefail

if [[ -e "$1" ]]; then
  ffmpeg -i "$1" -f image2pipe -c:v ppm - 2>/dev/null \
    | "$(dirname "$0")"/aggregator
else
  youtube-dl "$1" -o - \
    | ffmpeg -i - -f image2pipe -c:v ppm - 2>/dev/null \
    | "$(dirname "$0")"/aggregator
fi
